version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml

volumes:
  postgres_data:
