version: '3.9'

services:
  web:
    build: .
    ports:
  - "8000:8000"

    environment:
      - DJANGO_DEBUG=1
      - DJANGO_SETTINGS_MODULE=mysite.settings
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.9.1
    container_name: loki-1
    ports:
      - "3100:3100"
    volumes:
      - ./loki_data/chunks:/loki/chunks
      - ./loki_data/index:/loki/index
      - ./loki_data/cache:/loki/cache
      - ./loki_data/wal:/loki/wal
      - ./loki_data/compactor:/loki/compactor
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
    command: -config.file=/etc/loki/loki-config.yml
    user: root


volumes:
  postgres_data:
